hard_tabs = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
unstable_features = true
blank_lines_upper_bound = 5
fn_params_layout = "Tall"
newline_style = "Unix"
overflow_delimited_expr = false
struct_lit_single_line = true
use_try_shorthand = true
where_single_line = true
